[env:uno]
platform = atmelavr
board = uno
framework = arduino

; --- Haptic Device Configuration (Toggle build between 1DOF and 2DOF) ---
; To Compile 1DOF (src/main.cpp) uncomment line 8 and comment line 10
build_src_filter = +<*> -<main2DOF.cpp>
; To Compile 2DOF (src/main2DOF.cpp) uncomment line 10 and comment line 8
; build_src_filter = +<*> -<main1DOF.cpp>

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    paulstoffregen/Encoder @ ^1.4.4
    paulstoffregen/TimerOne @ ^1.2.0
    cstdint
    https://github.com/ConnormMcKelvey/Haplink.git
