[env:uno]
platform = atmelavr
board = uno
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    paulstoffregen/Encoder @ ^1.4.4
    paulstoffregen/TimerOne @ ^1.2.0
    cstdint
    https://github.com/ConnormMcKelvey/Haplink.git
